[[author]]
    username = "kochie"
    fullName = "Robert Koch"
    email = "robert@kochie.io"
    avatar = "kochie.png"
    bio = "hello"
    [[socialMedia]]
        name = "twitter"
        link = "https://twitter.com/kochie"
        icon = ["fab", "twitter"]
        color = "#1da1f2"
        tracking = "T36VD8UN"
    [[socialMedia]]
        name = "instagram"
        link = "https://instagram.com/rkkochie"
        icon = ["fab", "instagram"]
        color = "#833ab4"
        tracking = "EJCVUQXE"
    [[socialMedia]]
        name = "linkedin"
        link = "https://linkedin.com/in/rkkochie"
        icon = ["fab", "linkedin"]
        color = "#0077b5"
        tracking = "RMXXVNIC"
    [[socialMedia]]
        name = "website"
        link = "https://me.kochie.io"
        icon = ["fal", "globe"]
        color = "wheat"
        tracking = "SEQGQC1X"

[[tag]]
    name = "WebDev"
    blurb = "Articles related to Web Development and creating modern websites"
    [image]
        src = "web-development.jpg"

