### .github/workflows/dependabot_automerge.yml
### This workflow has access to secrets and a read-write token
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# permissions:
# down scope as necessary via https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token

jobs:
  do-stuff:
    runs-on: ubuntu-latest

    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build

      - run: npm test
